### ISSUE TITLE
save position inside the object => render Objects beside the tiles (Items etc.)

### ISSUE THREAD

**Issue by jeyj0** [DungeonDevs/PyEngine#1]
@Julisep 
Why was this added? The position is not needed in the object itself because it is given by the map. Is it needed for further use? Then in what way?

Objects and Tiles are the same in the engine, so no difference. :) 

Does this solve the TODO?

**Comment by KeineLimonade** [comment]
What about the Player and Items? They can no really be stored the same way as the tiles as the have to be above the tiles.

**Comment by jeyj0** [comment]
Tiles are walls as I understand it. Is it possible for an Item to be on the same place as the Player, another Item, a Wall or sth else? As I understand it there can only be one thing at one place. So there should be no problem...?

**Comment by KeineLimonade** [comment]
What about a ground layer?

**Comment by KeineLimonade** [comment]
Nevermind, we just can add another object under every object, so don´t worry.

**Comment by jeyj0** [comment]
Exactly. Already implemented a ground layer btw. And I added an attribute that can remove the ground layer the object.
